baseurl = "https://owarai.netlify.com/"
languageCode = "en-us"
title = "A minimal Hugo website"
theme = "hugo-xmin"
googleAnalytics = "UA-107230532-1"
disqusShortname = "owarai"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true
hasCJKlanguage = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于本站"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name ="文章"
    url = "/post/"
    weight = 5

[params]
    description = "我是简介"
    footer = "&copy; 伦敦之心地址 [Bilibili](https://space.bilibili.com/5382023) 2017 | [weibo](https://www.weibo.com/u/2784997275)"
