baseurl = "/"
languageCode = "en-us"
title = ""
theme = "hugo-xmag"
googleAnalytics = ""
disqusShortname = "owarai"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 12

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "订阅"
    url = "/index.xml"
[[menu.top]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.top]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.top]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.top]]
    name = "字幕组"
    url = "/fansub/"
    weight = 5
[[menu.top]]
    name = "加入我们"
    url = "/joinus/"


[params]
    description = ""
    summary_length = 200
    github_edit = "https://github.com/yihui/hugo-xmag/edit/master/exampleSite/content/"
    footer = "&copy; [OWARAICLUB](https://owarai.netlify.com/) 2017 | [转载规则](https://owarai.netlify.com/) | [加入我们](https://owarai.netlify.com/) | [FAQ](https://owarai.netlify.com/) | [关于我们](/about/)"

[params.text]
    back = "&larr; 返回首页"
    edit = "编辑此页 &rarr;"
    truncated = "&hellip;"

[params.banner]
    src = "/img/logo.png"

